### ISSUE TITLE
How use functional components in react

### ISSUE THREAD

**Issue by Zeph180** [Zeph180/math-magician#5]
Functional components in react are normal javascript objects that can be created using the function key word.

Functional components are presentational by default. Thanks to react 16 they can be given state using the useState hook.

The usestate hook takes two arguments ie the  data and a function that manipulates that data. eg const data = useState(numsArray, setNumsArray).
We need to import the hook from react before we can use it.  Typically at the top of the file. 

usStateAnd other hooks are first class citizens meaning the should always be defined at the top level of the function.

>

**Comment by prolajumokeoni** [comment]
Hi @Zeph180 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  functional components used 🚀  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
